### ISSUE TITLE
Selecting Partner vs IM

### ISSUE THREAD

**Issue by kschlenker** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#17]
On most tabs there is an ability to filter/view data by Partner _or_ IM. The only place that I could find where you could actually choose whether you want to use the Partner name or the IM name was on the Global04 Partner Contribution tab. It wasn't really intuitive that I'd have to go to that tab to be able to set the parameter for the rest of the workbook.

Short term suggestion: document this in the Intro/Notes/Users Guide tab & explain how the parameter filter on that tab controls views for the entire tableau workbook
Long term suggestion: consider alternative approaches to that might be a little easier for users. This might mean separating them out into two separate filters; having the IM/Partner toggle appear on more tabs; appear in the first tab only; appear in the first tab of each color-coded section, etc.

**Comment by noahbartlett** [comment]
Yeah, that's something that people weren't as excited about as I had hoped. People felt it just added clutter. The ability to look at either partner or IM is still there; but I took the toggle switch off out of the tabs. You are right though, it was left in Global4.

Since we are going to have an introduction page, that's where that toggle between IM and partner can happen. Since that toggle switch will affect all tabs, that is where it should go. If someone else wants to put it in, it is the parameter labeled "PP-IM"
