### ISSUE TITLE
Global Dashboard -Agency Contribution Tab - Option b data is wrong

### ISSUE THREAD

**Issue by kgichuhi** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#35]
Option b was created to improve the visualization of the Agency contribution tab.  However a couple of the percentages are incorrect in option b. There is also no ability to see the actual numbers.  Can we add in the ability to see the actual counts and investigate where the percentage is incorrect?

Agency contribution tab; TX_CURR, FY17; the total sums to 101% with USAID representing 42 and CDC 56% respectively.
Agency contribution tab option b; OU 'All', TX_CURR; FY17 - the total sums to 99% with USAID representing 42% and CDC 55%

**Comment by jrose202** [comment]
the chart is not as you describe - the numbers are 55% CDC, 41% USAID, 3% DoD, 1% HRSA. 

post a screenshot of the issue.

**Comment by kgichuhi** [comment]
Thanks - it's critical that the totals sum to 100% - it's the first thing people will look at and the absolute numbers will be compared to pano - super helpful to have the absolute numbers thanks.

**Comment by jrose202** [comment]
everything sums to 100%.  you just can't see the percents for HRSA and DoD on the horizontal chart as they are tiny spaces

both charts use "percent of total" to graph - if you take agencies out (e.g. dedup) you'll get different percentages but same absolute numbers,  

I would ask Jacob what he thinks the value of "dedup" is in these graphs

**Comment by noahbartlett** [comment]
FYI, you can't include dedup in the bar graph - because dedups are negative numbers, they make the bar charts unreadable. I think the chart that Jessica uploaded solves the problems. 

Closing this up. Re-open if this isn't what you need. 

Also, a reminder that everything posted on GitHub is 100% publicly accessible. I would suggest not posting screen-shots unless using publicly available data.
