### ISSUE TITLE
PMTCT 02: Positivity

### ISSUE THREAD

**Issue by nmcdavid** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#9]
Unknown age was not available in the Tableau Dashboard but is available in Panoram
![image](https://user-images.githubusercontent.com/36705660/42333034-a095a5ae-8047-11e8-8811-b4cb558dd3f5.png)

**Comment by nmcdavid** [comment]
I reviewed 4 OUs for their PMTCT_STAT and PMTCT_STAT_POS and noticed that the results for 20-24 and 25-49 age groups differ from Panorama. Here is the link to the excel sheet with [examples](https://drive.google.com/open?id=1nn7FyAtZaBZx7ALAjeVGvIb_U13nkGD3)

**Comment by noahbartlett** [comment]
OK. I figured out what was causing this error. It was something I had put in place to address another issue, which needs to be addressed by the group. In Pano, Fine age disaggs only begin to be counted in FY18Q2, even if there are fine age results in FY18Q1. Should the dashboard include those Q1 fine age disag numbers where they exist at the risk of being discrepant from Pano? 

Anyway, this issue is solved, but it may introduce a new issue vis-a-vis the Q1/Q2 fine age disaggs.
